export const SET_ERROR = 'SET_ERROR';
export const SET_AUTHENTICATION = 'SET_AUTHENTICATION';
export const SET_LOG_OUT = 'SET_LOG_OUT';
export const SET_SIGNUP_LOADING = 'SET_SIGNUP_LOADING';
export const SET_SIGNUP_RESPONSE = 'SET_SIGNUP_RESPONSE';
export const SET_SIGNUP_ERROR = 'SET_SIGNUP_ERROR';